package uy.edu.ort.arq.corba.idl;


/**
* uy/edu/ort/arq/corba/idl/CorbaPalabrasInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/uy/edu/ort/arq/corba/idl/CorbaPalabrasInterface.idl
* Wednesday, June 17, 2009 1:37:37 AM UYT
*/

public abstract class CorbaPalabrasInterfacePOA extends org.omg.PortableServer.Servant
 implements uy.edu.ort.arq.corba.idl.CorbaPalabrasInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("convertirPalabra", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // uy/edu/ort/arq/corba/idl/CorbaPalabrasInterface/convertirPalabra
       {
         String palabra = in.read_string ();
         String $result = null;
         $result = this.convertirPalabra (palabra);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:uy/edu/ort/arq/corba/idl/CorbaPalabrasInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CorbaPalabrasInterface _this() 
  {
    return CorbaPalabrasInterfaceHelper.narrow(
    super._this_object());
  }

  public CorbaPalabrasInterface _this(org.omg.CORBA.ORB orb) 
  {
    return CorbaPalabrasInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class CorbaPalabrasInterfacePOA
