package uy.edu.ort.arq.corba.idl;


/**
* uy/edu/ort/arq/corba/idl/CorbaPalabrasInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/uy/edu/ort/arq/corba/idl/CorbaPalabrasInterface.idl
* Wednesday, June 17, 2009 1:37:37 AM UYT
*/

public interface CorbaPalabrasInterfaceOperations 
{
  String convertirPalabra (String palabra);
} // interface CorbaPalabrasInterfaceOperations
