package uy.edu.ort.arq.corba.idl;


/**
* uy/edu/ort/arq/corba/idl/CorbaPalabrasInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/uy/edu/ort/arq/corba/idl/CorbaPalabrasInterface.idl
* Wednesday, June 17, 2009 1:37:37 AM UYT
*/

abstract public class CorbaPalabrasInterfaceHelper
{
  private static String  _id = "IDL:uy/edu/ort/arq/corba/idl/CorbaPalabrasInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, uy.edu.ort.arq.corba.idl.CorbaPalabrasInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static uy.edu.ort.arq.corba.idl.CorbaPalabrasInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (uy.edu.ort.arq.corba.idl.CorbaPalabrasInterfaceHelper.id (), "CorbaPalabrasInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static uy.edu.ort.arq.corba.idl.CorbaPalabrasInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CorbaPalabrasInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, uy.edu.ort.arq.corba.idl.CorbaPalabrasInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static uy.edu.ort.arq.corba.idl.CorbaPalabrasInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof uy.edu.ort.arq.corba.idl.CorbaPalabrasInterface)
      return (uy.edu.ort.arq.corba.idl.CorbaPalabrasInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      uy.edu.ort.arq.corba.idl._CorbaPalabrasInterfaceStub stub = new uy.edu.ort.arq.corba.idl._CorbaPalabrasInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static uy.edu.ort.arq.corba.idl.CorbaPalabrasInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof uy.edu.ort.arq.corba.idl.CorbaPalabrasInterface)
      return (uy.edu.ort.arq.corba.idl.CorbaPalabrasInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      uy.edu.ort.arq.corba.idl._CorbaPalabrasInterfaceStub stub = new uy.edu.ort.arq.corba.idl._CorbaPalabrasInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
