package uy.edu.ort.arq.corba.idl;

/**
* uy/edu/ort/arq/corba/idl/CorbaPalabrasInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/uy/edu/ort/arq/corba/idl/CorbaPalabrasInterface.idl
* Wednesday, June 17, 2009 1:37:37 AM UYT
*/

public final class CorbaPalabrasInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public uy.edu.ort.arq.corba.idl.CorbaPalabrasInterface value = null;

  public CorbaPalabrasInterfaceHolder ()
  {
  }

  public CorbaPalabrasInterfaceHolder (uy.edu.ort.arq.corba.idl.CorbaPalabrasInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = uy.edu.ort.arq.corba.idl.CorbaPalabrasInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    uy.edu.ort.arq.corba.idl.CorbaPalabrasInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return uy.edu.ort.arq.corba.idl.CorbaPalabrasInterfaceHelper.type ();
  }

}
